Clean up the file and fix browser instructions

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -100,40 +100,14 @@ jobs:
       matrix:
         node-version: [14, 16, 18]
 
-    # services:
-    #   rippled:
-    #     image: xrpllabsofficial/xrpld:latest
-    #     ports:
-    #       - 6006:6006
-    #     options: -v "${{ github.workspace }}/rippled/":"/config/" --health-cmd="wget localhost:6006 || exit 1" --health-interval=5s --health-retries=10 --health-timeout=2s
-    #     env: { ENV_ARGS: "-a --start" }
 
     steps:
       - uses: actions/checkout@v3
-          # /usr/bin/docker create --name rippled-service --label rippled-container --network ${{ job.container.network }} --network-alias rippled -p 6006:6006 -v "${{ github.workspace }}/ci-config/":"/config/" --health-cmd="wget localhost:6006 || exit 1" --health-interval=5s --health-retries=10 --health-timeout=2s -e "ENV_ARGS=-a --start" -e GITHUB_ACTIONS=true -e CI=true xrpllabsofficial/xrpld:latest
 
       - name: Run docker in background
         run: |
           docker run -d --rm --name rippled-service -p 6006:6006 -v "${{ github.workspace }}/ci-config/":"/config/" --health-cmd="wget localhost:6006 || exit 1" --health-interval=5s --health-retries=10 --health-timeout=2s -e "ENV_ARGS=-a --start" -e GITHUB_ACTIONS=true -e CI=true xrpllabsofficial/xrpld:latest
-      # - uses: addnab/docker-run-action@v3
-      #   with:
-      #     image: xrpllabsofficial/xrpld:latest
-      #     options: --network-alias rippled -p 6006:6006 -v ${{ github.workspace }}/ci-config/:/config/ -e HOST=localhost -e PORT=${{ job.services.rippled.ports['6006'] }}
-      #     run: |
-      #       echo "Started docker container with config:"
-          # echo "Install nvm"
-          # curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
-          # export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
-          # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
 
-          # echo "Install proper version of node and npm"
-          # nvm install {{ matrix.node-version }}
-          # cat config/rippled.cfg
-          # npm i -g npm@7 --registry=https://registry.npmjs.org
-          # npm --version
-          # npm ci
-          # npm run build
-          # npm run test:integration
       - name: See what ports are in use
         run: |
           netstat -ano -p tcp
@@ -182,27 +156,11 @@ jobs:
       matrix:
         node-version: [14.x] # This just needs to be compatible w/ puppeteer
 
-    services:
-      rippled:
-        image: xrpllabsofficial/xrpld:latest
-        ports:
-          - 6006:6006
-        options: -v "${{ github.workspace }}/rippled/":"/config/" --health-cmd="wget localhost:6006 || exit 1" --health-interval=5s --health-retries=10 --health-timeout=2s
-        env: { ENV_ARGS: "-a --start" }
-
     steps:
 
-      - name: ls
+     - name: Run docker in background
         run: |
-          ls -a
-
-      - name: pwd
-        run: |
-          pwd
-
-      - name: cat file
-        run: |
-          cat ${{ github.workspace }}/ci-config/rippled.cfg
+          docker run -d --rm --name rippled-service -p 6006:6006 -v "${{ github.workspace }}/ci-config/":"/config/" --health-cmd="wget localhost:6006 || exit 1" --health-interval=5s --health-retries=10 --health-timeout=2s -e "ENV_ARGS=-a --start" -e GITHUB_ACTIONS=true -e CI=true xrpllabsofficial/xrpld:latest
 
       - name: Setup npm version 7
         run: |
@@ -228,4 +186,9 @@ jobs:
         run: npm ci
 
       - run: npm run build
-      - run: npm run test:browser
+
+      # Docker stop must be in same step as integration test so it doesn't get skipped if tests fail.
+      - name: Run browser test & stop docker once completed
+        run: |
+          npm run test:browser
+          docker stop rippled-service
